# Site settings
name: 刘晓倩
location: 甘肃
company: 中国
position: 在读博士（北京交通大学）
github: https://github.com/xiaoqianliu1
facebook: https://www.facebook.com/
email: liuxiaoqian@163.com

baseurl: "/"

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown

